from libs import unsorted_linked_list

Link = unsorted_linked_list.UnsortedLinkedList()
Link.append(10)
Link.append(20)
Link.append(30)
Link.append(40,True)
Link.traverse()
Link.insert(60,2)
Link.traverse()
Link.insert(70,1)
Link.traverse()
Link.remove(70)
Link.traverse()
Link.remove(40)
Link.traverse()
Link.append(34)
Link.traverse()
Link.delt(2)
Link.pop()
print(Link.len())
Link.traverse()